testsubject <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/test/subject_test.txt')
xtest <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/test/X_test.txt')
ytest <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/test/y_test.txt')
d1 <- cbind(testsubject, ytest)
test <- cbind(d1, xtest)
trainsubject <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/train/subject_train.txt')
xtrain <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/train/X_train.txt')
ytrain <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/train/y_train.txt')
d1 <- cbind(trainsubject, ytrain)
train <- cbind(d1, xtrain)
combineddataset <- rbind(test, train)
d1 <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/features.txt')
features <- t(d1[2])
col <- c('subject', 'activity')
header <- c(col, features)
header <- make.names(header, unique=TRUE)
colnames(combineddataset) <- header
activities <- read.table('C:/Users/carminep/Downloads/getdata%2Fprojectfiles%2FUCI HAR Dataset (2)/UCI HAR Dataset/activity_labels.txt')
colnames(activities) <- c('activity', 'activity_desc')
library(dplyr)
dataset <- left_join(combineddataset, activities)
dataset <- select(dataset, subject, activity_desc, contains("mean"), contains("std"))
write.table(dataset, file = 'C:/Users/carminep/datasciencecoursera/GettingCleaningData/Week4Assignment/Dataset1.txt')
dataset2 <- dataset %>% group_by(activity_desc, subject) %>% summarise_all(funs(mean))
write.table(dataset2, file = 'C:/Users/carminep/datasciencecoursera/GettingCleaningData/Week4Assignment/Dataset2.txt')